[server]
host: all
port: 7125
klippy_uds_address: /home/lava/printer_data/comms/klippy.sock

[machine]
provider: none

[authorization]
trusted_clients:
    172.18.0.0/16
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.0.0.0/8
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[zeroconf]
mdns_hostname: U1

[snapmakercloud]

[exception_manager]

[client_manager]

[repeater]

[mqtt]
address: 127.0.0.1
port: 1883
client_id: moonraker
mqtt_protocol: v5
status_interval: 2
default_qos: 1
